image: 'registry.scoopit.io/scoopit-runner'

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cargo build --all --all-targets --color=always
    - RUST_BACKTRACE=1 cargo test

release:
  stage: build
  only:
    - tags
  artifacts:
    paths:
      - target/release/binrep
      - target/release/binrep-batch
  script:
    - cargo build --release --all --all-targets --color=always

binrep_publish:
  stage: deploy
  only:
    - tags
  script:
    - chmod +x target/release/binrep
    - target/release/binrep push binrep $CI_COMMIT_TAG target/release/*

