image: 'registry.scoopit.io/scoopit-runner'

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cargo build --all --target=x86_64-unknown-linux-musl --all-targets --color=always
    - RUST_BACKTRACE=1 cargo test
    ## basic upload / download checks
    - target/debug/binrep push binrep-ci-test auto target/debug/binrep target/debug/binrep-batch
    - target/debug/binrep sync binrep-ci-test latest sync-output-dir

release:
  stage: build
  only:
    - tags
  artifacts:
    paths:
      - target/release/binrep
      - target/release/binrep-batch
  script:
    - cargo build --target=x86_64-unknown-linux-musl --release --all --all-targets --color=always

binrep_publish:
  stage: deploy
  only:
    - tags
  script:
    - chmod +x target/release/binrep
    - target/release/binrep push binrep $CI_COMMIT_TAG target/release/*

