image: 'registry.scoopit.io/scoopit-runner'

stages:
  - build

build:
  stage: build
  script:
    - cargo build --all --all-targets --color=always
    - RUST_BACKTRACE=1 cargo test

release:
  stage: build
  only:
    - tags
  artifacts:
    paths:
      - target/release/binrep
  script:
    - cargo build --release --all --all-targets --color=always
    - RUST_LOG=binrep=info binrep push binrep $CI_COMMIT_TAG target/release/binrep

