image: 'registry.scoopit.io/scoopit-runner'

variables:
  CARGO_BUILD_TARGET: x86_64-unknown-linux-musl


stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cargo build --all --all-targets --color=always
    - RUST_BACKTRACE=1 cargo test
    ## basic upload / download checks
    - target/x86_64-unknown-linux-musl/debug/binrep push binrep-ci-test auto target/x86_64-unknown-linux-musl/debug/binrep target/x86_64-unknown-linux-musl/debug/binrep-batch
    - target/x86_64-unknown-linux-musl/debug/binrep sync binrep-ci-test latest sync-output-dir

release:
  stage: build
  only:
    - tags
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/binrep
      - target/x86_64-unknown-linux-musl/release/binrep-batch
  script:
    - cargo build --release --all --all-targets --color=always

binrep_publish:
  stage: deploy
  only:
    - tags
  script:
    - chmod +x target/x86_64-unknown-linux-musl/release/*
    - target/x86_64-unknown-linux-musl/release/binrep push binrep $CI_COMMIT_TAG target/x86_64-unknown-linux-musl/release/*

