[package]
name = "binrep"
version = "0.1.0"
authors = ["Philippe GASSMANN <pgassmann@scoop.it>"]
edition = "2018"

[dependencies]
serde={ version = "1.0", features=["derive"] }
sane = "0.2"
structopt = "0.2"
failure = "0.1.5"
ring="0.14.6"
rand="0.6.5"
shellexpand = "1.0.0"

[[bin]]
name="binrep"
path="src/bin/binrep.rs"
